### ISSUE TITLE
General pool concept

### ISSUE THREAD

**Issue by michaelsjackson** [JoepVanlier/Hackey-Patterns#2]
Not sure about the current pool concept. Now, in v0.05 it seems the pool is managed internally, so it copies patterns, in unknown ways, additionally into the arrange.

Another concept could be, using the time line until a specific marker (PLAYLIST) as a pool. Also hackey-pattern sequencing would start from this specific marker and later.

Examples:
pool: bars 1..100, marker PLAYLIST at bar 101, playlist: 101..infinity
pool: bars 1..300, marker PLAYLIST at bar 301, playlist: 301..infinity

In short, we can always extend the pool space, by simply moving the marker PLAYLIST to a later location. Hackey-Patterns would auto-shift all used patterns to their correct position then.

Its additional advantage is you can use any available song/arrange and make a pattern variant, by adding a new marker PLAYLIST at the end somewhere, then start editing the excel table, like in buzz.

One more advantage, no special pool needs to be managed, the arrange of Reaper, before the marker PLAYLIST is the pool, well defined, no special cases, no strange pooled copies in arrange, no multiple pastes.

Time selection can be used for item/pattern editing.
Loop points can be used for looped playback, e.g. some range after marker PLAYLIST.
In short you can play something else while editing other patterns. You only need to unlink time selection and loop points.

**Comment by JoepVanlier** [comment]
I've considered this option before, but decided against it for the following reasons:

- The problem is that it is not possible to check what used to be after the marker once the marker is moved. For that I would have to keep track of where the marker would have been last time the pool was used. Once it's moved, I will suddenly be stuck with duplicate copies with the same GUID in the pool, unless I store the old pool position. This one is a relatively minor issue.

- Copies have to be pooled anyway, since that is also how it behaves in buzz. Change one pattern, all patterns with that name change. I plan to have a shortcut to depool an item on the playlist though.

- It feels much more natural that when you decide to use arrange view, you edit patterns in the song, rather than the pool. You will also mostly be looking at the playlist section of the project rather than the pools, since when the song is playing, this is where the project cursor will be.

- If you really prefer to only edit in the pool, you can use it in the way you describe already. The only difference is that the pool is at the end. If you create new patterns in the pool directly, it will not do any extra copying and since the items will always be pooled automatically, there is really not much of a difference.

- Once feature complete, I will move the pool to much later point in the project (probably allow the user to set it in the config file) and add a marker where it is located. I want people to be able to add things to the arrange section by hand, and have the plugin deal just with it by copying a pattern it has not yet seen to the pool. This so you can work with both the sequencer and normal reaper editing functionality transparently. That's why I have that action which when you add a new item to the arrange view, HP will automatically add it to the pool.

**Comment by JoepVanlier** [comment]
It's true though, that having the user manage the pool himself would be easier. Especially when it comes to automation items, where the API still leaves something to be desired.

**Comment by michaelsjackson** [comment]
To me it feels unnatural or distracting if something is added to the arrange (the pooled copy at the end) what I did not put there myself, but ok, you are the boss. The other way around, I would always know what I put there first, before PLAYLIST are my patterns, from which I can contruct other things. But I will look and learn.  :)

pool + playlist feels to me a much more universal and simpler concept, but why not using something more complicated, if it works in the end. Thanks master sai'ke for starting this!

**Comment by JoepVanlier** [comment]
Well, originally, the plan was to make it transparent to buzz. Creating new patterns from HT or HP would create new ones in the pool only. They wouldn't be on your playlist until you place them. The idea would also be to not have the user mess with the pool. But I still want the regular reaper actions to also still work and have the plugin deal with those.

The reason that I need physical copies for the pool is that I always need to maintain a copy of a pattern. I use this for two purposes, one to have a copy, but two, to know the true length of the item. In reaper one can resize items, and the original length of the item is no longer available through the API. This means that in order not to lose patterns, know their original length at creation and index them all, I have to copy things with GUIDs that I haven't seen yet into the pool. If you'd run out of pool space and shift the marker to where the playlist already begins, you'd suddenly add a bunch of stuff to what is interpreted as the pool. I'd have to add handling to deal with double GUIDs and worse, double automation items in the pool then.

I can see if I can make the pool delimited by a two sided range and make the copy behavior optional, if this helps you. Then I guess we can put it at the front or end as we desire.

I will support break, I just haven't gotten round to coding it yet. :)
